spin:
  publicPem: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyCm1454RUoRoedttdOS7
    G7Hmrn0qnVNF2wkS3lPT7lKn9Ml2JzuwktrKU+UUNhE8cUZZsLK5fzk7HBLUSZqo
    2tFfXz+4A2vKponOUk15ZYHbHQz71H0zLlgEvj0/ljMLLFZjFH6BgJjOcOYgXhC4
    qFFwch8MFN4DjUTroBJn0W2RwLhSneYay9v+AFxLrKQEXDeclgW9ODqKAp1caifz
    OEgegTcdppnep9+aBNTAVwil0r5rIidQHP9823MZJL/3zDnpEHPogjHaIXL8iCOj
    grwWltbY2LHbyAneZ6Ms0oaNenpw6GTD87LO92RtbN9Yp72DjwKPf0CeYCIjC6Yy
    L0Acsz6CfUs6FXcTgSAkJKf6OacB9EB7rD4sgPLa3ANReuxCgC6A4Fe6oSUNrPHd
    hHaaTu6SZmbz+P0mveh4ap8/z5eN5pdCUAqbsX1W+fQf4hdcvtWETZTq+l/vCa5/
    glzjPq/WXu1ksyZqOmXOdfMK0UzXsBVS/+rBDQB5ph4YyqkviUJD1vGXadi0s3Na
    9Z2z3OyTZROPPaLcVnOrjUtVJvOk9KAJdcyYoJOmQy9OGlWdIl0u5zNcL+9bOanD
    yskOFLoWPqwpmC4ZXRDEp5RTrBs5N4mLZKw2Uhud3PU+ucLGM0fqDdczewVLH/Uo
    dTmkRcFz0mFAG/lNzkp/0GkCAwEAAQ==
    -----END PUBLIC KEY-----

  privatePem: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJJwIBAAKCAgEAyCm1454RUoRoedttdOS7G7Hmrn0qnVNF2wkS3lPT7lKn9Ml2
    JzuwktrKU+UUNhE8cUZZsLK5fzk7HBLUSZqo2tFfXz+4A2vKponOUk15ZYHbHQz7
    1H0zLlgEvj0/ljMLLFZjFH6BgJjOcOYgXhC4qFFwch8MFN4DjUTroBJn0W2RwLhS
    neYay9v+AFxLrKQEXDeclgW9ODqKAp1caifzOEgegTcdppnep9+aBNTAVwil0r5r
    IidQHP9823MZJL/3zDnpEHPogjHaIXL8iCOjgrwWltbY2LHbyAneZ6Ms0oaNenpw
    6GTD87LO92RtbN9Yp72DjwKPf0CeYCIjC6YyL0Acsz6CfUs6FXcTgSAkJKf6OacB
    9EB7rD4sgPLa3ANReuxCgC6A4Fe6oSUNrPHdhHaaTu6SZmbz+P0mveh4ap8/z5eN
    5pdCUAqbsX1W+fQf4hdcvtWETZTq+l/vCa5/glzjPq/WXu1ksyZqOmXOdfMK0UzX
    sBVS/+rBDQB5ph4YyqkviUJD1vGXadi0s3Na9Z2z3OyTZROPPaLcVnOrjUtVJvOk
    9KAJdcyYoJOmQy9OGlWdIl0u5zNcL+9bOanDyskOFLoWPqwpmC4ZXRDEp5RTrBs5
    N4mLZKw2Uhud3PU+ucLGM0fqDdczewVLH/UodTmkRcFz0mFAG/lNzkp/0GkCAwEA
    AQKCAgAEEEi3isV6QeLnGmvR9DTSPp3azAK59+9Sn5AJAHWsgHQVdaOW71DJ4nQ6
    GMv8vwPVnuKCQlaevRg0nTM/HUsxSg/gHKiNNTqDgAe2xwjgZS8AG3vfV/1agwHx
    pMeuMnIXH9faGilh5XhHdXyRvFArZp/cSUITCGDVFOGdudHuwAU1/uf6eanwmpJB
    Cp6krh3Ci4R7zTkGs7WKkQxHwXDgIyKvZ+GLuNL64IC9eV5ARhYrvZ7qLhcjx5IO
    2HrZsqYCuOhA48GEJyPxCucSknqm1E+3FzyGxbGbEYw42Wi3C3FC28qABU+vGmG2
    Rw0rqSshGKlblWc5Y6Pzeq3wdhrNro4AjMgIGTDBQGfqI3JxPx7M2TaC1HVxg8px
    uZz39/L494wxSbKhwi8eahJufdUvMW2zVjnSnuhkQ9KVisxCDLoYA9ZtWX0QQ2TB
    exxuPuH9Rbt+bGTL1H3YV+wtWNGfxhc/DwYvlgKNKdX6Q7dWGBr7eO5oLtbk6l8Z
    y1/G9wW/CLQ6dHmRABUKyU1u/SHIX+XtUIVFbGGd6UKScx0QNgGGqsxwtvEhyg8q
    OdhJ27ZVE6iIRaQ3iIdBWyeVSfsn7oaftG8qYsPIb/0xORcnj65KJgjKLubAMo8t
    11jfFsHuQ3MAClbl7tOTOcPHDlLLcXNvuFdzEcHWGUBIDerQ6QKCAQEA8zHEQspT
    JsFakFrLKzHipd/ZFsRXsyHlVEQBIlC4iLQ/XBvJmIkkCe03IKkmim8RKKPNu9Va
    spDDjK/c0fBQ+HAs7Hej1mNCun8Ug3UQbdEGVpQhUlwNeWH1MFhMhsxFLXcQq4KH
    N/R7pp+rNav2M6Bu/Q7n7I7n3RjCOFUM2FvYxP4go4lvKGryXVX0/a1HgyQU5UhH
    vyTPI+xr8xBDODgPPdVCfqN78L0e3bJNFxC3/fPfVmYYUk1gKuKJnMMuIJ1Vaggu
    wNYQroCTvUL1s+GmR27Y9oMQv1LUEREfBu/NLuLp/NHpiqwWAVmpQKAt+GnjK5li
    KCEgKsxLYXDNrQKCAQEA0rPibBIK7fOwxNNZ0dDvEWP6xtDLy1mW9XXqr8r28781
    f5LITvv6GkKrHGCRg0wBFpHS49Hzm/MASxHj/zFBxZGiGrH6zweyslU0nrKbcUpO
    lBf0NtMpovUW7qWZRYdyutGljAZgeUi9V1u2ZvOvF22LNxU+DvfmKxfC2YrMfeF9
    4N8fj8/1wUbaHxFW7lzd+pBRUoJAIFyFm809+NwRlt484PyGSK3kdvKjF4BhdWza
    gOlxjlatEG5dZdFmJ0bbowrSitxb7yRZpxykVEzA0fJ9DvfVD7nm9lcmM5aRK8d2
    2LgwT6CzHoqnz+VgXcjgXXBrSVaPKUP0MI+w251tLQKCAQAiRtBnrYacvsHZ+MIL
    +4L7aBp75/6IY+2ju9YBFSl9MxJ/E/eNBT9MGuAbPVwOROtBNB0qLT8UTe0R5jOU
    b2+qJH1gcthnviPIj2K/yH8hS0W+bDBqIElR42mgf8GBekcByndSBRqz20SWToje
    DrervSAHkNNFdzrc4cF2GR6vW/qogTzub893/eLdHuFh48thg3NigZaDLVf4szjf
    0Fn5EYWsbGNr3/T3EGDKVHgjGRslsvq2fbtN1lQIl1dX/faBaEuCn1afnUxKnBq2
    oTpqORKrnMb9r6lrnev/387ktmXQBvF9zcRB5FFRrWZ6klkIWzxGh97a0xhqj9LM
    EA8dAoIBAE7eHGudWU/2Pn1+Kwm5bjMRPGY883t7XmEksSL6EvPr54eIFshR0y0P
    NWNa1jzSLzoWfVzfUpNWIw72dGQqONdOCuJ5KktiM0ZDVH3ulvaR/NW8HaKD6frg
    SKQtgjCfYZeCL7g5DtV3H8BaSO1CW5CmZUzJ+7+4lQQeUcYCCUc5J1gLzJGVIwUk
    kzK719FDG6fVa0s6C+zRFQXbjk3fegoBx8HjZBRCWtkXO2rpmBFPHH7SYroHwaH7
    3aPl/JnJER93RpXJo/PgpFpEA1K2pBox7RO0OqE3Ubd1qYv32QENGXRHhXXYzhMp
    jWTpE+gm76yqDs6VwuKMWBPxRR7/T0UCggEAE8tWj8ZbaszW4V5ZAJlG++b2u1V3
    jTzyh2hyIGuOtV0AdegWyRFl0TBIXUsaj9ISZFJjEL0lFbv4eUdhefJyj2EGuX8S
    nBV3AraLS3TScFkEqiL4xk606sbC3uUtZCW5rIcQfAnJV13bmzoEk6JgldjhOe9u
    EZLX89nFVvRscFXuwqTR3lAyTgvt5S7iAPXIPjJQtVCaKTMoby9q/q00RZpKCip2
    h0uQGP+LWXGdNEsiJziArdKuL9G2ayvdXv4KyWjpGhyLl+OiKE23IO7b6kn7BQkc
    6jVupzzJa2JuXs5PpXHRt3Kc8VBk5Ot2wlfT96O7yyiuTquIL1NOBIxNoA==
    -----END RSA PRIVATE KEY-----


server:
  error:
    include-stacktrace: never
