spin:
  certificatePem: |
    -----BEGIN CERTIFICATE-----
    MIIFEjCCAvoCCQCQk/JuWDfYWzANBgkqhkiG9w0BAQsFADBLMQswCQYDVQQGEwJE
    RTEQMA4GA1UECAwHSGFtYnVyZzEQMA4GA1UEBwwHSGFtYnVyZzEYMBYGA1UEAwwP
    Sm9oYW5uZXMgSmFzcGVyMB4XDTIxMTExMTE3Mzg1MVoXDTIyMTExMTE3Mzg1MVow
    SzELMAkGA1UEBhMCREUxEDAOBgNVBAgMB0hhbWJ1cmcxEDAOBgNVBAcMB0hhbWJ1
    cmcxGDAWBgNVBAMMD0pvaGFubmVzIEphc3BlcjCCAiIwDQYJKoZIhvcNAQEBBQAD
    ggIPADCCAgoCggIBALQYEi7iSi1fSJc8YMpdm3u6uaQm/K7X/G3sW8hDDdFD55Sx
    JaOMzjsB2DyXBEpU6iu1Dvq0/vLU6gkz60Zw+kOhDvJKt/5ABJS90dkgEkPy+DCb
    OWEA4+2bLXtt9a6BmKylewJxRhQjnPtLENIC2H9y76SMddEeHqA1Bw+YSB8WpuXK
    3LgAB+cEun0pH3K3UEt2xKMjVWPNVGb29xAVg8JIzodv7BnU6Q/8shLHm8CASRGr
    AavidJAW2II6tLkNTsB3/NsEywFJ5IRPDk4cMTW9vG05iKyGvAtDJGSGaNAwJ4/1
    UKeXPXWDcphnrzFb47r9xi5BI3HgovUbLcF6UFWtDSeWsFGGI4KqjW8HRo+5q26o
    LBZA89PrhoM9hdjyUGD0UPEDHgednP3dAd1gksYJsJv/126q3o1idOHPPOSkBH6n
    tD1Z+XNlLo9kn9HNB87prwCZQS3FPERBC7gecVZz6q+Y2RjENjrpEdgmloe1SDuX
    0SxRygLAp8ZP9x41UUaETyBbCXjXXOpbilrJFaXiaNAMc7ljpesV6RGqzvUiZk/7
    niVLRBd/dw6wm2p4WTHuQJU5uMeWwDSiKoVssPsRhq/50w9sbAJ9ZsvT3JvZ4cve
    N+J29yAo8E+baup2AvYnMIT9kfWT+DVLZd6ZB0X7Sj/z83Pl6zUfdvq1dCUVAgMB
    AAEwDQYJKoZIhvcNAQELBQADggIBAF5D3qR6LvvT9/kY+TFdNcnpccahNedI2NV0
    U8WId+kdIgy6KUQPmjDuR0nKHRTuvWeAwzXR/ByGpi7f9J1a9aV63dtY8VUShjBc
    w6Q4YqHS+4iIlzNZfYKJ42naY0stzXvt6qJAW9pDAiPFkT5bPAI1JSGf9wGOj5pG
    iDQ0ZZ9puTE2WJpFZdOKxQDIqTJuoRXckeUPn1vqYdOXLBpkFHIRAok3k1gAsJvB
    fztZzgQfZeI9WGyVNjJaO9KLvzuB6u29UVyUDSYQWFn0RRV2gyOKe7cGAcJm94YP
    JFZv18asgorTvXD3yogYGtWUw2MO+jdHc68Wr1l/s4K69YFaVOsZ7WCEizjMIr3e
    j95VTnz0qV0b5ZtDwGM44XRXUEcKZEJ/BITHYo+uKY1lCyW8BQiSvyEm2JK7//JK
    +ecOUJ6Y80R+Yfi/IWYRureVvr7BDb6g1Wkml35Rin8aZbKQeI6hkgOK5g1yqLhU
    ZpAxtSJf7zWLDcQqPNq2LWS0+16/1nstaYI8CtNmVC2kJxvplC3+nQMR0wYpleNl
    CZYDhR5zI26/xs9uVuk0uOTdB01vMUsCTU7gmSrFdy48AA2UMlvdroAAczaDmf6o
    EGSyY3lshqc9ypUDkCuBDOvq5PAeADxWNp+5VO6xVcneYgeL+/OgdKT9opeK7OQ8
    NkXwIYjN
    -----END CERTIFICATE-----

  privatePem: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQC0GBIu4kotX0iX
    PGDKXZt7urmkJvyu1/xt7FvIQw3RQ+eUsSWjjM47Adg8lwRKVOortQ76tP7y1OoJ
    M+tGcPpDoQ7ySrf+QASUvdHZIBJD8vgwmzlhAOPtmy17bfWugZispXsCcUYUI5z7
    SxDSAth/cu+kjHXRHh6gNQcPmEgfFqblyty4AAfnBLp9KR9yt1BLdsSjI1VjzVRm
    9vcQFYPCSM6Hb+wZ1OkP/LISx5vAgEkRqwGr4nSQFtiCOrS5DU7Ad/zbBMsBSeSE
    Tw5OHDE1vbxtOYishrwLQyRkhmjQMCeP9VCnlz11g3KYZ68xW+O6/cYuQSNx4KL1
    Gy3BelBVrQ0nlrBRhiOCqo1vB0aPuatuqCwWQPPT64aDPYXY8lBg9FDxAx4HnZz9
    3QHdYJLGCbCb/9duqt6NYnThzzzkpAR+p7Q9WflzZS6PZJ/RzQfO6a8AmUEtxTxE
    QQu4HnFWc+qvmNkYxDY66RHYJpaHtUg7l9EsUcoCwKfGT/ceNVFGhE8gWwl411zq
    W4payRWl4mjQDHO5Y6XrFekRqs71ImZP+54lS0QXf3cOsJtqeFkx7kCVObjHlsA0
    oiqFbLD7EYav+dMPbGwCfWbL09yb2eHL3jfidvcgKPBPm2rqdgL2JzCE/ZH1k/g1
    S2XemQdF+0o/8/Nz5es1H3b6tXQlFQIDAQABAoICAQCRI8kbsdGYKW9mOwnCbZhO
    KhlMuwLvoi/VIySBC9FJ8pDjW7T6zxKxqXXstsSFZ1Pl76Bn2pCRgZgv3IDjn0+C
    S32xNRh9tng6q5RAiUFPM7Rj7+VZUQ9gQaxxChhzEAzMLv0o5cNVnbH5L/EZX6O9
    axLJKU4WP1DtSm8rWU3eiDHvhgNF4vh7bWsiTY8Ds8rpVol49JPvv94isSxB8STj
    4itYKZI860L9WGjnC6lxhbHdpFTPgszwBwlsQwW9EYWDRfApTv6QRk39d30O5Feg
    eQ4vdKu6Z0eLSAw/W7eC+RwZP9pFhnTIjSxAuWcOv4CUBcu/IU4Ai8qpAMNqZznv
    yCYN3TmGzfb1dMkRTZ4UDkzlmkes4n6rLGC0x2pkC+PpBqXKjkssLBAUNObAOnv/
    /M7lD/yOfGWswq07Y3nocUrIDuASmTt+Lgs2uV9H0keYC27zWM5mBIx3RaPnYL/i
    unuO6dhXg2YEu2Mo+JqltNHJ/l7eGZssyKJUn/1r+Ave5Lj6pGvMkpfgFvuWzmkR
    PxtVUXXxS/CA7G32OZK0WhKJwizVDNjXj1F07B/lXgBaSQ74+oY93tvBlWielt58
    YdzrJrKEEoAr/aFBMb3hoLGfH8KFB8D72BkXHvMAqf0IjyQgzToB2hDgIf5J6kUb
    Qz6u2SJFYKMmlMG+FteSjQKCAQEA3ctNyj8wZsGBlKgECi/W1cCnuESEdrLGS5Mt
    QmEpNaOIIrYVPc9fXRjMNGbB46ONu4CFEjvPH4wAAgmJJ1X8jOaXEFpmD6+/De4u
    3d5PtoTaE6GuicAP//izhbDVbc4WDayZ0jctnLDw9E7X9Ypc9fCfxgezjmOHjS5m
    4p1gAUWlsXIRXqCwaNjPnzozBozLCYRhD1y16Mp16cSIkiJU9CLzr9k8MMpY6rIT
    krXJpHEdRgdjyUeypDO5L/d/IjaEVUQHIH9+LWgYUXot50yphz2bjxm+BKwVmVqL
    DOHGPFfQOKLA81qn7VRN52LUTtKQ0BdvX2p1VITKdBgJRG960wKCAQEAz95ljHIy
    EKd348WGVOdKtA3PpqqLwTs223xjAQ5EZ8WWB8FxoKV81QZhjRmMZ9qkeGZ5AZk1
    CIXIkgcSpLnObgGsqfofInmOX0zg3r828X+YjPImVm976aIF6RvwO+Xz3phY8BKM
    tpvmL18Kd9zprhguxwcKONcHoIjBcegMg0YmeEtkZEWb3MHU4Kgqsne3wm8Hf4O3
    fE13vJ2UVrImzN6bu+FqCviExWYIijoEAYqt15iTWD1uW7Hkuu0qdg6ESSO+7bRb
    UbaquyyHf1OooxggxdcMd6dc0VCCUEz0S0ii+g/XzJGlD109VkOSlSnZFmzCYS5v
    1NK0oklCPKOfdwKCAQEAy0kgD5NDJauOvVYR/dRDML/X+giy8KiDH5nSDdlIECXH
    DSme5nw/h/DGmfDlHWQ27/in/0JaYSvMhhF/aFJjnDFtnEt+6DnI/1ekFS9CGKRD
    zWKPuyoSgCbPRGYD+RS/GeFtS0PPxqJW91Wcky0ybykRCEzewk9vWnOBUYu1BvVz
    HOTUDstxZWfzRJnvUr2RCzQOUipDgQ6wbIb6NhbJjsrKWA7gIEgWn2aAkiOUoegb
    UKhNSZsxnVbbEZ/jItSdDhm//oVcfPm/8E3v7ORTLeXFwq9xfo7LbTeT40a8j2pd
    Ksvh1irtZ5WxobbvqR9OI6yXI/lLeSAM/8NYGyWiiQKCAQAjy/LE6u2APLbCvMNT
    X7lXpIE7/Gaw0heyWItcJS7WiAo8L633skf7D2xBNkMdp2NncI4qHk4pt5BAxYMK
    Zw0LmLI5W199Ol2wP7cB5P/7OrP0ocbEX9KA+2v1JuCKECGdFbNLNIaS8+oCAmX1
    GlALsRJtJ+M0wqMHnEVj7kgpWy1IzgLt2abrr12PiqY/saoti51I8k/o0hZqnuBq
    xac05KkBA+KVHRMQQ2/5DeCeu1kQpa/KJFoa5Fm1bx4+0mUpi0RX/xUyzzg7n4F+
    BdQmsgMCzvPQrzumuCyY04fGZy3ZzlylV/eK282yS1S0504BNJ2MyshraBW/VMpZ
    UvwlAoIBAHW1X061Ren0sPwqIYmf23VfTjNLfLylD6VlxD6XXkRID2vvhGAzdUeC
    6R40FnhZHHnQH9pDqnH+tO9tgfP+buub3VliOahssN01O1daSzhStEMIn98KIbag
    lAxKKTxuf/uKp5NDKhBLLdwtfNIgJy9i7ZZaOR+5H1ER7t9MVuEaLblqSAyhu52m
    SISK3gny/n1R7tbGNgUwvb/fpSki6WPaZxwDeRVpHd8EcLCZMPWy4t+NnKM8oYLM
    2zf4T65pb6XvdD+TQ31dBoH8dGJ0ZbTHOXitMTpydNW4FwcDKxzxAuCQux9AJeYh
    LE+YvCy4QeD0IKlPUoqQ6tfW1FG5qlI=
    -----END PRIVATE KEY-----


server:
  error:
    include-stacktrace: never
